### ISSUE TITLE
hole into the sewers

### ISSUE THREAD

**Issue by mattymatty97** [MinecraftReplicaofCodeLyoko/City#1]
![2018-09-20_15 46 17](https://user-images.githubusercontent.com/33039934/45822723-635ad100-bcec-11e8-9af6-f361003b9d8d.png)
![2018-09-20_15 46 08](https://user-images.githubusercontent.com/33039934/45822729-65bd2b00-bcec-11e8-8e18-01affa5b1050.png)

severs first node right barrier wall, on the bottom left side there is a 2 blocks hole

**Comment by mattymatty97** [comment]
fast XD

**Comment by KaruzoDEV** [comment]
Fixed. Also checked the rest of the sewers barriers so there are no more holes.
