### ISSUE TITLE
jumping a 2 block wall

### ISSUE THREAD

**Issue by mattymatty97** [MinecraftReplicaofCodeLyoko/City#2]
it's possible to jump every 2 block wall if the top block of the wall is breakable by a vanilla user ( without plugins)
breaking it and jumping forward while breaking will glitch you into the top block and then jumping again on top of it
![2018-09-20_15 57 13](https://user-images.githubusercontent.com/33039934/45823558-40312100-bcee-11e8-86d3-904af7f8e075.png)
![2018-09-20_15 57 21](https://user-images.githubusercontent.com/33039934/45823564-41fae480-bcee-11e8-85c8-a85c3943b659.png)
![2018-09-20_15 57 27](https://user-images.githubusercontent.com/33039934/45823572-458e6b80-bcee-11e8-8032-0bff00fe19d4.png)
![2018-09-20_15 57 30](https://user-images.githubusercontent.com/33039934/45823577-47f0c580-bcee-11e8-9028-c4d54eb3a626.png)

**Comment by mattymatty97** [comment]
the fact is that this cant be prevented through a plugin.
the only way is blocking with a 3 block wall or an 2 block unbreakable wall :/

**Comment by GoodOldJack12** [comment]
Perhaps I should try finally installing NoCheatPlus. only if it doesnt break anything else tho.

**Comment by KaruzoDEV** [comment]
Fixed in Science Building's fence.
