### ISSUE TITLE
glitching up a floor ( trapdoor needed )

### ISSUE THREAD

**Issue by mattymatty97** [MinecraftReplicaofCodeLyoko/City#3]
find a trapdoor that is 1 or 2 block under a floor
jump on it when open ( if at 1 block ) closed (if at 2 block)
close / open it
jump while breaking the floor block
once the block will break you'll glitch upside to the first free block
( you'll get a small damage )
![2018-09-20_16 04 48](https://user-images.githubusercontent.com/33039934/45824281-ea5d7880-bcef-11e8-9147-582b24a7181b.png)
![2018-09-20_16 05 05](https://user-images.githubusercontent.com/33039934/45824283-ec273c00-bcef-11e8-8b0f-b07c408ffafa.png)
![2018-09-20_16 08 01](https://user-images.githubusercontent.com/33039934/45824289-ee899600-bcef-11e8-8fdb-51dfbf4bc704.png)

**Comment by KaruzoDEV** [comment]
Fixed in Science Building's classrooms
