### ISSUE TITLE
open a iron door/trapdoor

### ISSUE THREAD

**Issue by mattymatty97** [MinecraftReplicaofCodeLyoko/City#4]
if there is a door and from the opposite side of the wall there is a lever/button
you can open it by keeping the action button clicked while breaking the block where the redstone is standing
![2018-09-20_16 14 48](https://user-images.githubusercontent.com/33039934/45824601-ab7bf280-bcf0-11e8-91d1-55efad2056b6.png)
![2018-09-20_16 14 58](https://user-images.githubusercontent.com/33039934/45824603-adde4c80-bcf0-11e8-990e-9d91a1b31774.png)
![2018-09-20_16 15 08](https://user-images.githubusercontent.com/33039934/45824606-afa81000-bcf0-11e8-8ea1-c7c31977d170.png)
![2018-09-20_16 15 11](https://user-images.githubusercontent.com/33039934/45824609-b0d93d00-bcf0-11e8-86df-3a6ee85c70e9.png)

**Comment by GoodOldJack12** [comment]
might assign these to a 'worldguard bug' tag and close it if no solution is found, for future reference

**Comment by KaruzoDEV** [comment]
Will check in the future
